#############################################################################
# Makefile for building: WiiDance
# Generated by qmake (2.01a) (Qt 4.6.2) on: Mi 30. Jun 09:44:51 2010
# Project:  WiiDance.pro
# Template: app
# Command: d:\entwicklung\qtsdk\qt\bin\qmake.exe -spec d:/Entwicklung/QtSDK/qt/mkspecs/win32-g++ -win32 -o Makefile WiiDance.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = d:/entwicklung/qtsdk/qt/bin/qmake.exe
DEL_FILE      = rm
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir
COPY          = cp
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: WiiDance.pro  d:/Entwicklung/QtSDK/qt/mkspecs/win32-g++/qmake.conf d:/Entwicklung/QtSDK/qt/mkspecs/qconfig.pri \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/qt_functions.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/qt_config.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/exclusive_builds.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/default_pre.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/win32/default_pre.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/debug.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/debug_and_release.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/default_post.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/win32/default_post.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/win32/rtti.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/win32/exceptions.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/win32/stl.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/shared.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/warn_on.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/qt.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/win32/opengl.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/win32/thread.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/moc.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/win32/windows.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/resources.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/uic.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/yacc.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/lex.prf \
		d:/Entwicklung/QtSDK/qt/mkspecs/features/include_source_dir.prf \
		d:/Entwicklung/QtSDK/qt/lib/qtmaind.prl
	$(QMAKE) -spec d:/Entwicklung/QtSDK/qt/mkspecs/win32-g++ -win32 -o Makefile WiiDance.pro
d:/Entwicklung/QtSDK/qt/mkspecs/qconfig.pri:
d:/Entwicklung/QtSDK/qt/mkspecs/features/qt_functions.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/qt_config.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/exclusive_builds.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/default_pre.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/win32/default_pre.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/debug.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/debug_and_release.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/default_post.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/win32/default_post.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/win32/rtti.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/win32/exceptions.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/win32/stl.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/shared.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/warn_on.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/qt.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/win32/opengl.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/win32/thread.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/moc.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/win32/windows.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/resources.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/uic.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/yacc.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/lex.prf:
d:/Entwicklung/QtSDK/qt/mkspecs/features/include_source_dir.prf:
d:\Entwicklung\QtSDK\qt\lib\qtmaind.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -spec d:/Entwicklung/QtSDK/qt/mkspecs/win32-g++ -win32 -o Makefile WiiDance.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
